Forum-Dyskusyjne/Models/MakeThreadViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web.WebPages;
using Forum_Dyskusyjne.Areas.Admin.Controllers;
using Forum_Dyskusyjne.Areas.Utils;
using Forum_Dyskusyjne.Validators;
using Ganss.XSS;

namespace Forum_Dyskusyjne.Models
{
    public class MakeThreadViewModel
    {
        [Required]
        [StringLength(40)]
        [Display(Name="Thread title", Description = "Thread title")]
        public string ThreadTitle { get; set; }
        
        [Required]
        public int CategoryId { get; set; }

        private string _content;
        [Required]
        [StringLength(500)]
        [AllowWords(ErrorMessage = "Post content contains disallowed words!")]
        [Display(Name="First post", Description = "First post")]
        public string FirstPostContent
        {
            get => _content;
            
            set
            {
                // Sanitizing html input with using https://github.com/mganss/HtmlSanitizer (which default rules are great)
                var sanitizer = new HtmlSanitizer();
                sanitizer.AllowedTags.Clear();
                sanitizer.AllowedTags.UnionWith(JsonUtils.ReadStringListFromJson(AllowedTagsController.JsonPath));
                var body = sanitizer.Sanitize(value);
                if (body.IsEmpty())
                {
                    _content = null;
                }
                else
                {
                    _content = body;
                }
            }
        }
    }
}

Forum-Dyskusyjne/Controllers/ForumController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Forum_Dyskusyjne.DAL;
using Forum_Dyskusyjne.Models;
using Microsoft.AspNet.Identity;
using Thread = Forum_Dyskusyjne.Models.Thread;

namespace Forum_Dyskusyjne.Controllers
{
    public class ForumController : Controller
    {
        private ForumDbContext db = new ForumDbContext();

        public ActionResult Index(int index)
        {
            var forum = db.Categories.Find(index);
            
            return View(forum);
        }

        [Authorize]
        public ActionResult MakeThread(int index)
        {
            var th = new MakeThreadViewModel
            {
                CategoryId = index,
                FirstPostContent = "",
                ThreadTitle = ""
            };
            
            return View(th);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> MakeThread(MakeThreadViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            else if (!this.TryValidateModel(model))
            {
                ModelState.AddModelError(nameof(MakePostViewModel.Content), "Post content contains prohibited HTML tags!");
                return View(model);
            }

            var newThread = new Thread
            {
                Author = db.Users.Find(User.Identity.GetUserId()),
                Category = db.Categories.Find(model.CategoryId),
                IsPinned = false,
                ThreadTitle = model.ThreadTitle
            };
            db.Threads.Add(newThread);

            var firstPost = new Post
            {
                Author = db.Users.Find(User.Identity.GetUserId()),
                Body = model.FirstPostContent,
                Thread = newThread
            };
            db.Posts.Add(firstPost);
            await db.SaveChangesAsync();

            return RedirectToAction("Index", new { index = model.CategoryId });
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Forum-Dyskusyjne/Controllers/ThreadController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Forum_Dyskusyjne.DAL;
using Forum_Dyskusyjne.Models;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Collections;
using System;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Collections.Generic;

namespace Forum_Dyskusyjne.Controllers
{
    public class ThreadController : Controller
    {
        private ForumDbContext db = new ForumDbContext();

        public ActionResult Index(int index)
        {
            Thread thread = db.Threads.Find(index);
            if (thread == null)
            {
                return View("Error");
            }
            
            thread.Views++;
            db.SaveChanges();
            
            return View(thread);
        }

        [ChildActionOnly]
        [Authorize]
        public ActionResult MakePost()
        {
            return PartialView("_MakePost");
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> MakePost(MakePostViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Index", db.Threads.Find(model.ThreadId));
            }
            else if (!this.TryValidateModel(model))
            {
                ModelState.AddModelError(nameof(MakePostViewModel.Content), "Post content contains prohibited HTML tags!");
                return View("Index", db.Threads.Find(model.ThreadId));
            }

            var post = new Post
            {
                Author = db.Users.Find(User.Identity.GetUserId()), Body = model.Content,
                Thread = db.Threads.Find(model.ThreadId)
            };
            db.Posts.Add(post);
            await db.SaveChangesAsync();

            return RedirectToAction("Index", new { index = model.ThreadId });
        }


        [Authorize]
        public async Task<ActionResult> Report(int threadID , int postID)
        {
            var AdminRoleID = db.Roles.Where(r => r.Name.Equals("Admin")).Single().Id;
            List<User> admins = db.Users.Where(u => u.Roles.FirstOrDefault().RoleId == AdminRoleID).ToList(); ;
            User reportee = db.Users.Find(User.Identity.GetUserId());
            string title = "Report by user: " + User.Identity.GetUserName() + " on thread:" + db.Threads.Find(threadID).ThreadTitle;
            string content = " Link do wątku: " +  Url.Action("Details", "Threads",new { area = "Admin", id = postID }) +"\n" + "Treść postu: " + db.Posts.Find(postID).Body;
            foreach (User adm in admins)
            {
                Message report = new Message()
                {
                    SendDate = DateTime.Now,
                    Sender = reportee,
                    Title = title,
                    Text = content,
                    Receiver = adm,
                    OrginalSender = reportee.UserName,
                    OrginalReciver = adm.UserName,
                    Seen = false,
                };
                db.Messages.Add(report);
            }
            await db.SaveChangesAsync();

            return RedirectToAction("Index", new { index = threadID });
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Forum-Dyskusyjne/Views/Forum/Index.cshtml
@model Forum_Dyskusyjne.Models.Category

@{
    ViewBag.Title = @Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row d-flex">
    <h3 class="col-6 justify-content-start">@Model.ParentCategory.Name / @Model.Name</h3>
    @if(User.Identity.IsAuthenticated)
    {
        <a class="offset-3 col-2 mb-1 btn btn-primary justify-content-end" href='@Url.Action("MakeThread", "Forum", new { index=Model.CategoryId })'>Add thread!</a>
    }
</div>

<table class="table table-hover">
    <thead class="thead-dark">
    <tr>
        <th>
            Thread name
        </th>
        <th>
            Views
        </th>
        <th>
            Posts
        </th>
        <th>
            Last posted
        </th>
    </tr>
    </thead>
    
    <tbody>
@foreach (var item in Model.Threads.Where(m => m.IsPinned))
{
        <tr onclick="location.href = '@Url.Action("Index", "Thread",new { index=item.ThreadId })'" class="table-primary">
            <td>
                <h5>📌@item.ThreadTitle</h5>
                @item.Author.UserName
            </td>
            <td>
                @item.Views
            </td>
            <td>
                @item.Posts.Count
            </td>
            <td>
                @item.Posts.Last().CreatedTime.ToLocalTime()
            </td>
        </tr>
}
@foreach (var item in Model.Threads.Where(m => m.IsPinned == false))
{
        <tr onclick="location.href = '@Url.Action("Index", "Thread",new { index=item.ThreadId })'">
            <td>
                <h5>@item.ThreadTitle</h5>
                @item.Author.UserName
            </td>
            <td>
                @item.Views
            </td>
            <td>
                @item.Posts.Count
            </td>
            <td>
                @item.Posts.Last().CreatedTime.ToLocalTime()
            </td>
        </tr>
}
    </tbody>
</table>

Forum-Dyskusyjne/Views/Forum/MakeThread.cshtml
@model Forum_Dyskusyjne.Models.MakeThreadViewModel

@{
    ViewBag.Title = "Make Thread";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("MakeThread", "Forum", FormMethod.Post, new { @class = "form-horizontal text-center", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>New thread</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    @Html.LabelFor(m => m.ThreadTitle, new { @class = "col-8 control-label" })
    <div class="form-group d-flex justify-content-center ">
        @Html.TextBoxFor(m => m.ThreadTitle, new { @class = "form-control col-8" })
    </div>
    @Html.LabelFor(m => m.FirstPostContent, new { @class = "col-8 control-label" })
    <div class="form-group d-flex justify-content-center ">
        @Html.TextAreaFor(m => m.FirstPostContent, new { @class = "form-control col-8", @rows = "4" })
    </div>
    @Html.HiddenFor(m=>m.CategoryId)
    <div class="form-group">
        <input type="submit" value="Post it!" class="btn btn-primary" />
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}